config/routes.rb
Rails.application.routes.draw do

    namespace 'api' do
      namespace 'v1' do
       resources :products
 
     end
    end
   devise_for :users
   resources :products
 
   resources :users
 
   
   
   root to: "users#index"end

app/models/product.rb
class Product < ActiveRecord::Base
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
belongs_to :user
  def self.search(search)
    if search 
      where(["category LIKE ?","%#{search}%"])
    elsif
      where(["name LIKE ?","%#{search}%"])
    elsif
      where(["price LIKE ?","%#{search}%"])
    else
      all
    end

  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
end

app/controllers/api/v1/products_controller.rb
module Api 
    module V1
        class ProductsController < ApplicationController
            protect_from_forgery with: :null_session

            def index 
                if(params.has_key?(:category))
                    products = Product.where(category: params[:category])
                    render json: {status: 'SUSSES', message:'filtered products', data: products},status: :ok
                elsif
                    (params.has_key?(:name))
                        products = Product.where(name: params[:name])
                        render json: {status: 'SUSSES', message:'filtered products', data: products},status: :ok
                elsif
                    (params.has_key?(:price))
                        products = Product.where(price: params[:price])
                        render json: {status: 'SUSSES', message:'filtered products', data: products},status: :ok
                 elsif
                    (params.has_key?(:quantity))
                        products = Product.where(quantity: params[:quantity])
                        render json: {status: 'SUSSES', message:'filtered products', data: products},status: :ok        
                elsif
                    products = Product.search(params[:search]) 
                    render json: {status: 'SUSSES', message:'search results', data: products},status: :ok
                else    
                products = Product.order('created_at DESC');
                render json: {status: 'SUSSES', message:'Loaded products', data: products},status: :ok
                end
            
            end
            def show  
                products = Product.find(params[:id])
                render json: {status: 'SUSSES', message:'Loaded products', data: products},status: :ok
            end
            def create
                products = Product.new(product_params)
                
                if products.save
                    render json: {status: 'SUSSES', message:'Saved product', data: products},status: :ok
                else
                    render json: {status: 'ERROR', message:'Product not saved', data: products.error},status: :unprocessable_entity
                end
            end
            def destroy
                products = Product.find(params[:id])
                products.destroy
                render json: {status: 'SUSSES', message:'Deleted products', data: products},status: :ok
            end
            def update
                products = Product.find(params[:id])
                if products.update_attributes(product_params)
                render json: {status: 'SUSSES', message:'Updated products', data: products},status: :ok
                else
                render json: {status: 'ERROR', message:'Product not updated', data: products.error},status: :unprocessable_entity
                end
            end
            private

            def product_params
                    params.permit(:name, :category, :quantity, :price, :descritpion)
            end
        end         
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, expect: [:index]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    
    if(params.has_key?(:category))
      @products = Product.where(category: params[:category])
    elsif
      @products = Product.search(params[:search])  
    else
    @products = Product.all
    end


  end 

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_user.products.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :category, :quantity, :image, :price, :descritpion,)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :document, :kind, :status, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lojinha</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<tr>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

</body>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark my-nav justify-content-end">
   <div class="conteiner-fluid ">
        <%= link_to 'Login', user_session_path, class:"navbar-brand" %>
        <%= link_to 'Cadastrar', new_user_registration_path, class:"navbar-brand" %>
        <%= link_to 'Sair', destroy_user_session_path, method: :delete, class:"navbar-brand" %>
  </div>
  </nav>

  <style>.
 body { 
margin: 30px;

 }
.my-nav {
background-color: #836FFF

}
.my-col-1{
c #363636

}
.my-row {
  height: 1000px;
}

.my-col{
    height: 1000px;
 background-color: #363636
}

</style>

  <div class="row my-row">
    <div class="col col-lg-2  my-col">
       <div class="container my-conteiner">
       <p>
            <p><%= link_to 'Produtos', products_path, class: "btn btn-lg btn-block bg-light " %></p>
          <li class="dropdown">
  <button class="btn bg-light btn-lg btn-block dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Categotia
  </button>
  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
    <p><%= link_to 'Todos', products_path, class: "dropdown-item dropdown-item-lg" %></p>
    <p><%= link_to 'Comida', products_path(category:"Comida"),class:"dropdown-item " %></p>
    <p><%= link_to 'Bebida', products_path(category:"Bebida"),class:"dropdown-item" %></p>
    <p><%= link_to 'Limepza', products_path(category:"Limpeza"),class:"dropdown-item" %></p>
    <p><%= link_to 'Higiene', products_path(category:"Higiene"),class:"dropdown-item" %></p>
    
  </div>
</li>
        </tr>
    </div>
  </div>


<p c ass="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
    <div class="col">
      <%= yield %>
    </div>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, html: { multipart: true} do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
    <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>R$
  </div>
    <div class="field">
    <%= f.label :descritpion %><br>
    <%= f.text_field :descritpion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="jumbotron my-jumb">
  <div class="row">
   <div class="col">
    <h2 class="display-5">Produtos Disponiveis</h2>
   </div>
   <div class="col-md-lg-2 ">
 <%= form_tag products_path, :method => 'get' do%>
<%= text_field_tag :search, params[:search]%>
<%= submit_tag "Pesquisar", class:"btn btn-outline-success my-2 my-sm-0"%>
<%end%>
  </div>
 </div>    
</div>

<style>
.my-jumb {
  height: 1px;

}
</style>

<ul class="nav justify-content-end"> 
  <li class="nav-item">
<button type="button" class="btn btn-light"><%= link_to 'Novo Produto', new_product_path %></button>
  </li>
</ul>

<div class="container bg-light">
  <div class="row">
    <div class="col-sm-2">Produto</div>
    <div class="col-sm-2">Nome</div>
    <div class="col-sm-2">Categoria</div>
    <div class="col-sm-2">Quantidade</div>
  </div>
</div>
<p>
    <% @products.each do |product| %>
<div class="container">
  <div class="row ">
    <div class="col-sm-2 "><%= image_tag product.image.url(:thumb) %></div>
      <div class="col-sm-2"><%= link_to product.name, product_path(product) %></div>
    <div class="col-sm-2"><%= product.category %></div>
    <div class="col-sm-2"><%= product.quantity %></div> 
    <div class="col-sm-2"><button type="button" class="btn btn-light"><%= link_to 'Modificar', edit_product_path(product) %></button></div> 
    <div class="col-sm-2"><button type="button" class="btn btn-light"><%= link_to 'Excluir', product, method: :delete, data: { confirm: 'Tem certeza?' } %></button></div> 
    <br />
  
    <% end %>
<br>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron my-jumb">
  <div class="row">
   <div class="col">
    <h2 class="display-5">Informações do Produto</h2>
   </div>
   <div class="col-md-lg-2 ">
     <h1> <%= @product.name %></h1>
  </div>
 </div>    
</div>

<div class="container">
  <div class="row ">
  <div class="col-sm-4 "><%= image_tag @product.image.url(:medium) %></div>
<div class="col-sm-4">
<p>
<p>
  <h2><strong>Name:</strong>
  <%= @product.name %></h2>
</p>

<p>
  <h2><strong>Category:</strong>
  <%= @product.category %></h2>
</p>

<p>
  <h2><strong>Quantity:</strong>
  <%= @product.quantity %></h2>
</p>

<p>
  <h2><strong>Price:</strong>
 R$ <%= @product.price %> </h2>
</p>

</div>
</div>
</div>
<p>
  <h2><strong>Description:</strong>
  <%= @product.descritpion %></h2>
</p>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :document %><br>
    <%= f.text_field :document %>
  </div>
  <div class="field">
    <%= f.label :kind %><br>
    <%= f.number_field :kind %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Document</th>
      <th>Kind</th>
      <th>Status</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.document %></td>
        <td><%= user.kind %></td>
        <td><%= user.status %></td>
        <td><%= user.notes %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Document:</strong>
  <%= @user.document %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @user.kind %>
</p>

<p>
  <strong>Status:</strong>
  <%= @user.status %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @user.notes %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>